Repository FE-Training-S02/FE-Training-S02-FE-Final-Project_Huu-Nguyen-0023_Hieu-Cao-0022, pull requests merged in 2021-11, with the labels that each got.

#6 handle login, logout, change password
  final-project/package-lock.json
  final-project/package.json
  final-project/src/app/App.tsx
  final-project/src/app/pages/resetPassword/ChangePassword.tsx
  final-project/src/app/pages/updateInfo/UpdateInfo.tsx
  final-project/src/app/shared/components/authentication/SignUpEmail.tsx
  final-project/src/app/shared/helper/LocalAction.ts
  final-project/src/app/stores/user/actions.ts
  final-project/src/stylesheets/modules/_authenticationModal.scss
  final-project/src/stylesheets/pages/_updateUser.scss
Labels: t2-task, s4-wait-review

#3 [Task] Build header and section recommend post
  final-project/.env
  final-project/package-lock.json
  final-project/package.json
  final-project/public/index.html
  final-project/public/pictures/avatar.jpg
  final-project/public/pictures/picture1.jpg
  final-project/src/App.tsx
  final-project/src/api/axios-client.ts
  final-project/src/api/service-article.ts
  final-project/src/app/App.tsx
  final-project/src/app/pages/home/Home.tsx
  final-project/src/app/pages/home/partials/RecommendPost/Post.tsx
  final-project/src/app/pages/home/partials/RecommendPost/RecommendPost.tsx
  final-project/src/app/stores/app-reducer.ts
  final-project/src/app/stores/article/actions.ts
  final-project/src/app/stores/article/reducer.ts
  final-project/src/index.tsx
  final-project/src/share/component/header/Header.tsx
  final-project/src/share/component/skeleton-component/SkeletonElement.tsx
  final-project/src/share/component/skeleton-component/SkeletonRecommendArticle.tsx
  final-project/src/share/constants/articleConstant.ts
  final-project/src/share/helper/helper-function.ts
  final-project/src/share/model/article-interface.ts
  final-project/src/stylesheets/base/_base.scss
  final-project/src/stylesheets/base/_mixin.scss
  final-project/src/stylesheets/base/_variables.scss
  final-project/src/stylesheets/layout/_all.scss
  final-project/src/stylesheets/layout/_grid.scss
  final-project/src/stylesheets/layout/_header.scss
  final-project/src/stylesheets/modules/_all.scss
  final-project/src/stylesheets/modules/_button.scss
  final-project/src/stylesheets/modules/_card.scss
  final-project/src/stylesheets/modules/_skeleton.scss
  final-project/src/stylesheets/pages/_home.scss
  final-project/src/stylesheets/state/_text.scss
Labels: p3-medium, t2-task, s4-wait-review

#11 Handle UI header when user login
  package.json
  public/index.html
  src/app/pages/resetPassword/ChangePassword.tsx
  src/app/pages/updateInfo/UpdateInfo.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/components/authentication/SignInEmail.tsx
  src/app/shared/components/authentication/SignUpEmail.tsx
  src/app/stores/user/actions.ts
  src/app/stores/user/reducer.ts
  src/stylesheets/layout/_header.scss
Labels: s4-wait-review

#15 Handle follow user, interact post
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/pages/detail/Detail.tsx
  src/app/pages/handlePost/HandlePost.tsx
  src/app/pages/handlePost/partials/Editor.tsx
  src/app/pages/handlePost/partials/HandleImage.tsx
  src/app/pages/handlePost/partials/HandleTag.tsx
  src/app/pages/updateInfo/UpdateInfo.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/constants/UserConstant.ts
  src/app/shared/constants/articleConstant.ts
  src/app/shared/core/services/auth.ts
  src/app/shared/core/services/service-article.ts
  src/app/shared/models/Comment.d.ts
  src/app/shared/types/CommentHandle.d.ts
  src/app/shared/types/HandleFollow.d.ts
  src/app/shared/types/PostHandle.d.ts
  src/app/stores/article/actions.ts
  src/app/stores/article/reducer.ts
  src/app/stores/user/actions.ts
  src/app/stores/user/reducer.ts
  src/stylesheets/modules/_all.scss
  src/stylesheets/modules/_card.scss
  src/stylesheets/modules/_editor.scss
  src/stylesheets/modules/_loading.scss
  src/stylesheets/pages/_all.scss
  src/stylesheets/pages/_detail.scss
  src/stylesheets/pages/_handlePost.scss
Labels: t2-task, s4-wait-review

#21 [Task]continue complete detailpage and homepage
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/pages/detail/Detail.tsx
  src/app/pages/detail/partials/UserComment.tsx
  src/app/pages/home/Home.tsx
  src/app/pages/home/partials/Contact.tsx
  src/app/pages/home/partials/NewPost/NewPost.tsx
  src/app/pages/home/partials/NewPost/Post.tsx
  src/app/pages/home/partials/SlideItem.tsx
  src/app/pages/home/partials/Slider.tsx
  src/app/pages/home/partials/skeleton-component/SkeletonElement.tsx
  src/app/pages/home/partials/skeleton-component/SkeletonNewPost.tsx
  src/app/pages/home/partials/skeleton-component/SkeletonPost.tsx
  src/app/pages/newsfeed/Newsfeed.tsx
  src/app/pages/newsfeed/partials/NewsfeedItem.tsx
  src/app/pages/resetPassword/ChangePassword.tsx
  src/app/pages/wall/Wall.tsx
  src/app/pages/wall/partials/PostItem.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/components/authentication/AuthenticationModal.tsx
  src/app/shared/components/authentication/SignUpEmail.tsx
  src/app/shared/constants/articleConstant.ts
  src/app/shared/constants/postConstant.ts
  src/app/shared/core/services/apiWrapper.ts
  src/app/shared/core/services/axios-client.ts
  src/app/shared/core/services/service-article.ts
  src/app/shared/core/services/service-post.ts
  src/app/shared/helper/LocalAction.ts
  src/app/shared/helper/helper-function.ts
  src/app/shared/types/CommentHandle.d.ts
  src/app/stores/app-middleware.ts
  src/app/stores/article/actions.ts
  src/app/stores/article/reducer.ts
  src/app/stores/post/actions.ts
  src/app/stores/post/reducer.ts
  src/app/stores/user/actions.ts
  src/app/stores/user/reducer.ts
  src/stylesheets/base/_base.scss
  src/stylesheets/base/_variables.scss
  src/stylesheets/modules/_all.scss
  src/stylesheets/modules/_editor.scss
  src/stylesheets/modules/_list-comment.scss
  src/stylesheets/modules/_skeleton.scss
  src/stylesheets/pages/_detail.scss
  src/stylesheets/pages/_handlePost.scss
  src/stylesheets/pages/_home.scss
  src/stylesheets/pages/_wall.scss
Labels: p3-medium, t2-task, s4-wait-review

#20 Handle write and update post
  src/app/App.tsx
  src/app/pages/detail/Detail.tsx
  src/app/pages/handlePost/HandlePost.tsx
  src/app/pages/handlePost/partials/Editor.tsx
  src/app/pages/handlePost/partials/HandleImage.tsx
  src/app/pages/handlePost/partials/HandleStatus.tsx
  src/app/pages/handlePost/partials/HandleTag.tsx
  src/app/pages/handlePost/partials/PopupPublish.tsx
  src/app/pages/home/Home.tsx
  src/app/pages/updateInfo/UpdateInfo.tsx
  src/app/pages/wall/Wall.tsx
  src/app/pages/wall/partials/PostItem.tsx
  src/app/routes/AuthRoute.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/components/authentication/AuthenticationModal.tsx
  src/app/shared/components/authentication/SignInEmail.tsx
  src/app/shared/components/authentication/SignInModal.tsx
  src/app/shared/components/authentication/SignUpEmail.tsx
  src/app/shared/constants/UserConstant.ts
  src/app/shared/core/services/auth.ts
  src/app/shared/core/services/service-post.ts
  src/app/stores/post/actions.ts
  src/app/stores/post/reducer.ts
  src/app/stores/user/actions.ts
  src/app/stores/user/reducer.ts
  src/stylesheets/layout/_grid.scss
  src/stylesheets/modules/_authenticationModal.scss
  src/stylesheets/modules/_editor.scss
  src/stylesheets/pages/_all.scss
  src/stylesheets/pages/_detail.scss
  src/stylesheets/pages/_handlePost.scss
Labels: t2-task, in-progress

#22 Add navigate to write in header
  src/app/App.tsx
  src/app/pages/detail/Detail.tsx
  src/app/pages/handlePost/HandlePost.tsx
  src/app/pages/handlePost/partials/Editor.tsx
  src/app/pages/handlePost/partials/HandleTag.tsx
  src/app/pages/resetPassword/ChangePassword.tsx
  src/app/pages/updateInfo/UpdateInfo.tsx
  src/app/pages/updateInfo/partials/Avatar.tsx
  src/app/pages/updateInfo/partials/HandleBirthdate.tsx
  src/app/pages/updateInfo/partials/SelectGender.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/components/authentication/AuthenticationModal.tsx
  src/app/shared/components/authentication/SignInEmail.tsx
  src/app/shared/components/authentication/SignInModal.tsx
  src/app/shared/components/authentication/SignUpEmail.tsx
  src/app/shared/core/services/service-post.ts
  src/app/stores/post/actions.ts
  src/app/stores/user/reducer.ts
  src/stylesheets/layout/_header.scss
  src/stylesheets/modules/_authenticationModal.scss
  src/stylesheets/modules/_notification.scss
  src/stylesheets/pages/_detail.scss
  src/stylesheets/pages/_updateUser.scss
Labels: t2-task, s4-wait-review

#23 Task/20211120/continue complete detailpage and homepage
  src/app/pages/handlePost/partials/Editor.tsx
  src/app/pages/home/Home.tsx
  src/app/pages/home/partials/newsfeed/Newsfeed.tsx
  src/app/pages/home/partials/newsfeed/Post.tsx
  src/app/pages/home/partials/skeleton-component/SkeletonNewsfeed.tsx
  src/app/pages/wall/Wall.tsx
  src/app/pages/wall/partials/Post.tsx
  src/app/shared/components/authentication/SignUpEmail.tsx
  src/app/shared/core/services/service-post.ts
  src/app/stores/post/actions.ts
Labels: p3-medium, t2-task, s4-wait-review

#25 Handle upload image
  src/app/pages/handlePost/partials/PopupPublish.tsx
  src/app/pages/updateInfo/UpdateInfo.tsx
  src/app/pages/updateInfo/partials/Avatar.tsx
  src/app/shared/core/services/service-post.ts
  src/app/stores/post/actions.ts
Labels: t2-task, s4-wait-review

#28 Delete validate comment
  src/app/pages/detail/Detail.tsx
Labels: t2-task, s4-wait-review

#27 change convert time, fix layout of row, text-wrap, create wall page
  src/app/App.tsx
  src/app/pages/detail/Detail.tsx
  src/app/pages/detail/partials/UserComment.tsx
  src/app/pages/home/partials/newsfeed/Post.tsx
  src/app/pages/updateInfo/UpdateInfo.tsx
  src/app/pages/wall/Wall.tsx
  src/app/pages/wall/partials/Post.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/core/services/service-post.ts
  src/app/stores/post/actions.ts
  src/stylesheets/layout/_grid.scss
  src/stylesheets/layout/_header.scss
  src/stylesheets/modules/_list-comment.scss
  src/stylesheets/pages/_detail.scss
  src/stylesheets/pages/_home.scss
  src/stylesheets/pages/_updateUser.scss
  src/stylesheets/pages/_wall.scss
Labels: p3-medium, t2-task, s4-wait-review

#30 Make UI content for slider
  src/app/pages/home/partials/SlideItem.tsx
  src/app/pages/home/partials/Slider.tsx
  src/app/shared/core/services/service-post.ts
  src/app/stores/post/actions.ts
  src/stylesheets/pages/_home.scss
Labels: t2-task

#31 Make UI content for slider
  src/app/pages/home/partials/SlideItem.tsx
  src/app/pages/wall/Wall.tsx
  src/stylesheets/pages/_home.scss
Labels: t2-task, s4-wait-review

#32 Fix eslint to deploy
  src/app/App.tsx
  src/app/pages/detail/partials/UserComment.tsx
Labels: s4-wait-review

#33 Change redirect url in login social
  src/app/shared/components/authentication/SignInModal.tsx
Labels: t2-task, s4-wait-review

#42 Update button detail page
  src/app/pages/detail/Detail.tsx
  src/app/pages/wall/Wall.tsx
  src/app/pages/wall/partials/PopupFollow.tsx
  src/stylesheets/modules/_button.scss
  src/stylesheets/pages/_detail.scss
  src/stylesheets/pages/_wall.scss
Labels: t2-task, s4-wait-review
